name: drag_drop
version: 0.0.1
author: Pete Blois <github@blois.us>
description: Drag drop operations
homepage: https://github.com/peteblois/drag-drop
dependencies:
  browser: any
dev_dependencies:
  unittest: any
